export const REJECTION_REASON_CATEGORIES = [
  { category: 'Legal & Policy Violations', reasons: ['Illegal Product', 'Prohibited Service', 'Counterfeit Item', 'Stolen Property', 'Copyright Violation', 'Trade Restricted Item', 'Animal Abuse Or Illegal Pet Trade', 'Government Restricted Item', 'Adult Or Explicit Content', 'Offensive Or Hate Content'] },
  { category: 'Image Issues', reasons: ['No Image Uploaded', 'Low Quality Image', 'Blurry Image', 'Watermarked Image', 'Stock Image Used', 'Irrelevant Image', 'Misleading Image', 'Duplicate Images', 'Inappropriate Image', 'Image Contains Contact Info'] },
  { category: 'Video Issues', reasons: ['No Video Uploaded', 'Video Too Short / Too Long', 'Poor Video Quality', 'Shaky / Unclear Video', 'Video Does Not Match Product', 'Misleading Video Content', 'Offensive Content In Video', 'Background Audio Issues / Abuse', 'Video Contains Contact Info', 'Duplicate / Reused Video'] },
  { category: 'Title Issues', reasons: ['Title Too Short Or Vague', 'Title Contains Spam Keywords', 'Title Misleading', 'Title All Caps Or Symbols', 'Title Contains Contact Info', 'Title Language Not Allowed'] },
  { category: 'Description Issues', reasons: ['Description Too Short', 'Insufficient Details', 'Misleading Description', 'Keyword Spam', 'Contact Info In Description', 'External Links Present', 'Description Language Not Allowed', 'Duplicate / Copy Paste Content'] },
  { category: 'Pricing Issues', reasons: ['Price Not Mentioned', 'Unrealistic Price', 'Price Mismatch With Product', 'Price In Description Only', 'Multiple Prices Confusing'] },
  { category: 'Category & Location Issues', reasons: ['Wrong Category Selected', 'Multiple Categories Selected', 'Location Mismatch', 'Service Location Not Clear', 'Out Of Service Area'] },
  { category: 'Duplicate / Spam', reasons: ['Duplicate Ad', 'Repost Without Changes', 'Bulk Spam Posting', 'Similar Ads Multiple Times', 'Keyword Manipulation'] },
  { category: 'Missing / Invalid Details', reasons: ['Mandatory Fields Missing', 'Invalid Data Entered', 'Fake Information', 'Placeholder Content', 'Incomplete Specifications'] },
  { category: 'Contact & Redirection Violations', reasons: ['Phone Number In Title', 'Phone Number In Image', 'Email In Description', 'External Website Link', 'Social Media Redirect', 'Asking For Direct Contact'] },
  { category: 'Fraud / Risk Signals', reasons: ['Too Good To Be True', 'Advance Payment Request', 'Scam Pattern Detected', 'Suspicious Pricing Behavior', 'High Risk User History'] },
  { category: 'Language & Content Quality', reasons: ['Unsupported Language', 'Grammar Or Readability Issues', 'Irrelevant Content', 'Random Text Or Gibberish'] },
  { category: 'Product Authenticity Issues', reasons: ['Condition Misrepresented', 'Fake / Replica Not Declared', 'Missing Proof (IMEI, VIN, Serial No.)', 'Damaged Item Not Disclosed', 'Incorrect Specifications'] },
  { category: 'Seller Behaviour Issues', reasons: ['Repeated Policy Violations', 'Abusive Communication', 'Misuse Of Platform Features', 'Fake / Multiple Accounts', 'Non-Responsive Seller'] },
  { category: 'Transaction Violations', reasons: ['Refusing Platform Payment Flow', 'Asking For Offline Deal', 'Delivery Misuse / Refusal', 'Item Not Available After Payment', 'Cancellation Abuse'] },
  { category: 'AI Moderation Flags', reasons: ['AI Confidence Low', 'Auto-Detected Scam Pattern', 'Suspicious Metadata', 'Mismatch Between Video & Text', 'Duplicate Content Detected By AI'] },
  { category: 'Custom Moderator Input', reasons: [] },
]
